// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB77Bae94qSslzMwX1td43kJofCh-cRLA',
    appId: '1:20635740314:web:150eb027e7d4fac656d723',
    messagingSenderId: '20635740314',
    projectId: 'link-firebase-app',
    authDomain: 'link-firebase-app.firebaseapp.com',
    storageBucket: 'link-firebase-app.appspot.com',
    measurementId: 'G-QLMCBXRPTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2BYnRTUvayJWasMiQfPzjhMDf-R3fBoE',
    appId: '1:20635740314:android:1a1a3eba1cefeaf256d723',
    messagingSenderId: '20635740314',
    projectId: 'link-firebase-app',
    storageBucket: 'link-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTjffuv2IVZotExY-0EiNcemxTLWSjJgA',
    appId: '1:20635740314:ios:3390dd5a3bc6f65356d723',
    messagingSenderId: '20635740314',
    projectId: 'link-firebase-app',
    storageBucket: 'link-firebase-app.appspot.com',
    iosBundleId: 'com.salabatepapo.app.salabatepapo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTjffuv2IVZotExY-0EiNcemxTLWSjJgA',
    appId: '1:20635740314:ios:85cb09ef0011082c56d723',
    messagingSenderId: '20635740314',
    projectId: 'link-firebase-app',
    storageBucket: 'link-firebase-app.appspot.com',
    iosBundleId: 'com.salabatepapo.app.salabatepapo.RunnerTests',
  );
}
